version: "2"

services:

  apikey-pgdatabase:
    build:
      context: postgresql
    image: apikey-postgresql-database
    ports:
    - "5432:5432"
    environment:
        POSTGRES_PASSWORD: culture
        POSTGRES_USER: europeana
    restart: always

  apikey-appserver:
    build:
      context: tomcat
    image: apikey-tomcat-server
    environment:
      #Memory monitoring
      CATALINA_OPTS: '
            -XX:+UseConcMarkSweepGC
            -XX:NativeMemoryTracking=summary

            -Djava.rmi.server.hostname=172.18.0.4
            -Dcom.sun.management.jmxremote 
            -Dcom.sun.management.jmxremote.port=1099
            -Dcom.sun.management.jmxremote.rmi.port=1099
            -Dcom.sun.management.jmxremote.local.only=false 
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false
                '
      # -Xms512M -Xmx4096M -server -XX:+UseParallelGC
      #Debugging port
      JPDA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000

    #   Mount point for application in tomcat (the target folder on your workspace is directly mounted to the tomcat container)
    volumes:
      - ../target/apikey:/tomcat/webapps/apikey
    # Map ports from tomcat container to the local machine
    ports:
    #local:container
      #Tomcat port
      - "8081:8080"
      #Debug port
      - "8001:8000"
      #JMX Port
      - "1199:1099"
    restart: always