apiVersion: apps/v1
kind: Deployment
metadata:
  name: apikey-deployment
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: apikey
          image: europeana/apikey
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/info
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/info
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: secret
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/apikey.user.properties"
              readOnly: true
              subPath: apikey.user.properties
      volumes:
        - name: secret
          secret:
            secretName: apikey-secret