resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: apikey

# expects files to be in the same directory
secretGenerator:
  - name: apikey-secret
    files:
      - apikey.user.properties
