apiVersion: apps/v1
kind: Deployment
metadata:
  name: apikey-deployment
spec:
  template:
    spec:
      containers:
        - name: apikey
          # required to use local image
          imagePullPolicy: Never